#!/bin/bash
adb shell rm /storage/extSdCard/machinex-Mark87-N2.zip
adb shell rm /storage/extSdCard/machinex-Mark87-N3.zip
adb shell rm /storage/extSdCard/machinex-Mark87-N4.zip
adb shell rm /storage/extSdCard/machinex-Mark87-N6.zip
adb shell rm /storage/extSdCard/machinex-Mark87-N7.zip
adb shell rm /storage/extSdCard/machinex-Mark87-N8.zip
adb shell rm /storage/extSdCard/machinex-Mark87-N9.zip
adb shell rm /storage/extSdCard/machinex-Mark87-P1.zip
adb shell rm /storage/extSdCard/machinex-Mark86-11.zip
adb shell rm /storage/extSdCard/machinex-Mark86-20.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N1.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N10.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N11.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N12.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N14.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N15.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N16.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N17.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N2.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N3.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N4.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N5.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N6.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N7.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N8.zip
adb shell rm /storage/extSdCard/machinex-Mark86-N9.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P10.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P12.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P13.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P14.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P15.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P16.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P17.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P18.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P19.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P20.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P21.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P22.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P23.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P24.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P25.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P26.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P27.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P28.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P29.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P30.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P32.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P33.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P34.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P35.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P6.zip
adb shell rm /storage/extSdCard/machinex-Mark86-P9.zip
adb shell rm /storage/extSdCard/machinex-Mark86.zip
adb shell rm /storage/extSdCard/machinex-Mark87-N1.zip
adb shell rm /storage/extSdCard/machinex-Mark87-N10.zip
adb shell rm /storage/extSdCard/machinex-Mark87-N11.zip
