#!/bin/bash
cd /media/root/robcore/android/machinex
find arch/ -name "*.h" | xargs sed -i "s/ __cpuinit//g"
cd /media/root/robcore/android/machinex/arch
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/block
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/crypto
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/Documentation
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/drivers
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/firmware
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/fs
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/include
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/init
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/ipc
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/kernel
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/lib
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/mm
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/net
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/samples
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/scripts
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/security
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/sound
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/tools
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/usr
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
cd /media/root/robcore/android/machinex/virt
find -name "*.c" | xargs sed -i "s/ __cpuinit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuexit / /g"
find -name "*.c" | xargs sed -i "s/ __cpuinitdata//g"
find -name "*.c" | xargs sed -i "s/ __cpuinit$//g"
find -name "*.c" | xargs sed -i "s/^__cpuinit //g"
