#!/bin/bash
patch -p1 -R < "0057-some-fixes.patch"
patch -p1 -R < "0056-that-should-fix-it.patch"
patch -p1 -R < "0055-goddamn-device-trees-goddamn-ambiguous-platform-data.patch"
patch -p1 -R < "0054-fix-those.patch"
patch -p1 -R < "0053-aaand-the-headers-and-lets-see-if-she-builds.patch"
patch -p1 -R < "0052-a-little-bit-of-power-cleanup.patch"
patch -p1 -R < "0051-reverted-the-pm-stuff-but-kept-the-usb-stuff.patch"
patch -p1 -R < "0050-revert-me.patch"
patch -p1 -R < "0048-nope-gonna-grab-a-reference-for-which-irq-oneshots-t.patch"
patch -p1 -R < "0047-some-irqf_oneshot-additions.patch"
