#!/bin/bash
patch -p1 < "/root/machinex/patches/0109-timekeeping-Simplify-getboottime.patch"
patch -p1 < "/root/machinex/patches/0110-timekeeping-Remove-timekeeper.total_sleep_time.patch"
patch -p1 < "/root/machinex/patches/0111-timekeeping-Simplify-timekeeping_clocktai.patch"
patch -p1 < "/root/machinex/patches/0112-timekeeping-Provide-ktime_get_raw.patch"
patch -p1 < "/root/machinex/patches/0113-clocksource-Make-delta-calculation-a-function.patch"
patch -p1 < "/root/machinex/patches/0114-clocksource-Move-cycle_last-validation-to-core-code.patch"
patch -p1 < "/root/machinex/patches/0115-clocksource-get-rid-of-cycle-last.patch"
patch -p1 < "/root/machinex/patches/0116-timekeeping-Restructure-the-timekeeper-some-more.patch"
patch -p1 < "/root/machinex/patches/0117-timekeeping-Create-struct-tk_read_base-and-use-it-in.patch"
patch -p1 < "/root/machinex/patches/0118-timekeeping-Use-tk_read_base-as-argument-for-timekee.patch"
patch -p1 < "/root/machinex/patches/0119-timekeeping-Provide-fast-and-NMI-safe-access.patch"
patch -p1 < "/root/machinex/patches/0120-timekeeping-Minor-fixup-for-timespec64-timespec.patch"
patch -p1 < "/root/machinex/patches/0121-timekeeping-Rework-frequency-adjustments.patch"
patch -p1 < "/root/machinex/patches/0122-timekeeping-Use-cached-ntp_tick_length-when-accumula.patch"