#!/bin/bash
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0024-Linux-3.4.21.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0025-Linux-3.4.22.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0026-Linux-3.4.23.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0027-Linux-3.4.24.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0028-Linux-3.4.25.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0029-Linux-3.4.26.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0030-Linux-3.4.27.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0031-Linux-3.4.28.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0032-Linux-3.4.29.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0033-Linux-3.4.30.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0034-Linux-3.4.31.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0035-Linux-3.4.32.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0036-Linux-3.4.33.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0037-Linux-3.4.34.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0038-Linux-3.4.35.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0039-Linux-3.4.36.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0040-Linux-3.4.37.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0041-Linux-3.4.38.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0042-Linux-3.4.39.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0043-Linux-3.4.40.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0044-Fixed-some-compilation-errors.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0045-Linux-3.4.41.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0046-Linux-3.4.42.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0047-Linux-3.4.43.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0048-Linux-3.4.44.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0049-Linux-3.4.45.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0050-Linux-3.4.46.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0051-Linux-3.4.47.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0052-Linux-3.4.48.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0053-Linux-3.4.49.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0054-Linux-3.4.50.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0055-Linux-3.4.51.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0056-Linux-3.4.52.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0057-Linux-3.4.53.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0058-Some-compiling-errors-and-their-fixes.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0059-Linux-3.4.54.patch
patch -p1 -N -s < /media/root/robcore/android/Hulk-Kernel-V2-ref/patches/0060-Linux-3.4.55.patch
