#!/bin/bash
rm -rf arch/arm/mach-davinci
rm -rf arch/arm/mach-dove
rm -rf arch/arm/mach-imx
rm -rf arch/arm/mach-ixp2000
rm -rf arch/arm/mach-ixp23xx
rm -rf arch/arm/mach-ixp4xx
rm -rf arch/arm/mach-kirkwood
rm -rf arch/arm/mach-ks8695
rm -rf arch/arm/mach-mmp
rm -rf arch/arm/mach-mv78xx0
rm -rf arch/arm/mach-omap1
rm -rf arch/arm/mach-omap2
rm -rf arch/arm/mach-orion5x
rm -rf arch/arm/mach-prima2
rm -rf arch/arm/mach-prima2
rm -rf arch/arm/mach-pxa
rm -rf arch/arm/mach-s3c24xx
rm -rf arch/arm/mach-s3c64xx
rm -rf arch/arm/mach-sa1100
rm -rf arch/arm/mach-tegra
rm -rf arch/arm/mach-u300
rm -rf arch/arm/mach-vt8500
rm -rf arch/arm/plat-mxc
rm -rf arch/arm/plat-omap
rm -rf arch/arm/plat-pxa
rm -rf arch/arm/plat-samsung
rm -rf arch/avr32
rm -rf arch/blackfin
rm -rf arch/cris
rm -rf arch/frv
rm -rf arch/ia64
rm -rf arch/m32r
rm -rf arch/m68k
rm -rf arch/microblaze
rm -rf arch/mips
rm -rf arch/mn10300
rm -rf arch/openrisc
rm -rf arch/powerpc
rm -rf arch/s390
rm -rf arch/score
rm -rf arch/sparc
rm -rf arch/unicore32
rm -rf arch/x86
rm -rf arch/xtensa
