#!/bin/bash

patch -p1 -R < "0080-fixing-little-by-little.patch"
patch -p1 -R < "0079-cleanup.patch"
patch -p1 -R < "0078-iommu-msm-Handle-unmapping-of-PTE-properly.patch"
patch -p1 -R < "0077-iommu-msm-prevent-partial-mappings-on-error.patch"
patch -p1 -R < "0076-iommu-msm-Don-t-treat-address-0-as-an-error-case.patch"
patch -p1 -R < "0075-iommu-msm-check-range-before-mapping-for-IOMMU-v1.patch"
patch -p1 -R < "0074-lib-memory_alloc-Support-64-bit-physical-addresses.patch"
patch -p1 -R < "0073-dma-contiguous-Fix-warning-when-device-tree-is-disab.patch"
patch -p1 -R < "0072-msm-Update-meminfo-to-reflect-consecutive-memory-hol.patch"
patch -p1 -R < "0071-msm-correctly-handle-multiple-memory-holes.patch"
patch -p1 -R < "0070-ARM-proc-Add-Krait-proc-info.patch"
patch -p1 -R < "0069-drivers-Add-option-to-reserve-default-CMA-region.patch"
patch -p1 -R < "0068-cma-Allow-option-to-use-strict-memblock_reserved-mem.patch"
patch -p1 -R < "0067-cma-use-MEMBLOCK_ALLOC_ANYWHERE-for-placing-CMA-regi.patch"
patch -p1 -R < "0066-cma-Remove-restriction-on-region-names.patch"
patch -p1 -R < "0065-cma-Add-support-for-associating-regions-by-name.patch"
patch -p1 -R < "0064-cma-Fix-up-devicetree-bindings.patch"
patch -p1 -R < "0063-cma-Remove-__init-annotations-from-data-structures.patch"
patch -p1 -R < "0062-drivers-dma-contiguous-add-initialization-from-devic.patch"
patch -p1 -R < "0061-drivers-dma-contiguous-clean-source-code-and-prepare.patch"
patch -p1 -R < "0060-msm-simplify-placing-memory-pools.patch"

