0249-mm-move-readahead-syscall-to-mm-readahead.c.patch
0247-sched-rt-Add-missing-rmb.patch
0246-sched-Remove-one-division-operation-in-find_busiest_.patch
0245-sched-fix-the-theoretical-signal_wake_up-vs-schedule.patch
0244-sched-Consolidate-open-coded-preemptible-check.patch
0243-sched-Create-for_each_sd_topology.patch
0242-sched-Remove-the-useless-declaration-in-kernel-sched.patch
0241-sched-Move-update_load_-methods-from-sched.h-to-fair.patch
0239-sched-Simplify-can_migrate_task.patch
0238-sched-tracing-Allow-tracing-the-preemption-decision-.patch
0237-sched-name-spelling-misc-commits.patch
0236-sched-Fix-update_group_power-prototype-placement.patch
0235-sched-Remove-double-declaration-of-root_task_group.patch
0234-sched-Move-group-scheduling-functions-out-of-include.patch
0233-sched-Make-default_scale_freq_power-static.patch
0232-sched-Move-struct-sched_class-to-kernel-sched-sched..patch
0231-sched-Move-wake-flags-to-kernel-sched-sched.h.patch
0230-sched-Move-SCHED_LOAD_SHIFT-macros-to-kernel-sched-s.patch
0229-sched-do-not-use-cpu_to_node-to-find-an-offlined-cpu.patch
0228-sched-rt-Add-a-tuning-knob-to-allow-changing-SCHED_R.patch
0227-sched-Move-sched.h-sysctl-bits-into-separate-header.patch
0226-sched-Fix-signedness-bug-in-yield_to.patch
0225-sched-Bail-out-of-yield_to-when-source-and-target-ru.patch
0224-sched-Change-position-of-resched_cpu-in-load_balance.patch
0223-genlock-Taking-a-reference-for-lock-file.patch
0222-ARM-7494-1-use-generic-termios.h.patch
0221-block-fs-keep-track-of-the-task-that-dirtied-the-pag.patch
0220-mm-redefine-address_space.assoc_mapping.patch
0219-buffer-make-touch_buffer-an-exported-function.patch
0218-fs-buffer.c-do-not-inline-exported-function.patch
0217-remove-unnneded-ret-from-fs-block_dev.patch
0216-fs-block_dev.c-fix-iov_shorten-criteria-in-blkdev_ai.patch
0215-vfs-fix-O_DIRECT-read-past-end-of-block-device.patch
0214-fs-block-dev.c-fix-performance-regression-in-O_DIREC.patch
0213-block-remove-redundant-check-to-bd_openers.patch
0212-make-blkdev_put-return-void.patch
0211-fs-block_dev.c-no-need-to-check-inode-i_bdev-in-bd_f.patch
0210-compiler.h-add-support-for-function-attribute-assume.patch
0209-compiler-gcc-integrate-the-various-compiler-gcc-345-.patch
0208-compiler-gcc.h-neatening.patch
0207-compiler-introduce-__alias-symbol-shortcut.patch
0206-lib-make-memzero_explicit-more-robust-against-dead-s.patch
0205-lib-memzero_explicit-use-barrier-instead-of-OPTIMIZE.patch
0204-locking-arch-Add-WRITE_ONCE-to-set_mb.patch
0203-locking-Remove-atomicy-checks-from-READ-WRITE-_ONCE.patch
0202-kernel-make-READ_ONCE-valid-on-const-arguments.patch
0201-kernel-Fix-sparse-warning-for-ACCESS_ONCE.patch
0200-kernel-tighten-rules-for-ACCESS-ONCE.patch
0199-kernel-Change-ASSIGN_ONCE-val-x-to-WRITE_ONCE.patch
0198-compiler-Allow-1-and-2-byte-smp_load_acquire-and-smp.patch
0197-kernel-Provide-READ_ONCE-and-ASSIGN_ONCE-as-suggeste.patch
0196-lib-llist.c-fix-data-race-in-llist_del_first.patch
0195-lib-llist.c-remove-redundant-include.patch
0194-llist-fix-simplify-llist_add-and-llist_add_batch.patch
0193-ratelimit-fix-bug-in-time-interval-by-resetting-righ.patch
0192-radix-tree-fix-oops-after-radix_tree_iter_retry.patch
0191-radix-tree-fix-race-in-gang-lookup.patch
0190-PM-Avoid-calling-kfree-under-spinlock-in-dev_pm_put.patch
0189-PM-Runtime-Improve-prepare-handling-at-system-suspen.patch
0188-msm-ADSPRPC-Change-driver-initialization-to-late_ini.patch
0187-ptrace-introduce-signal_wake_up_state-and-ptrace_sig.patch
0186-Revert-power-pm8921-charger-change-BOOT_DONE-configu.patch
0185-power-pm8921-charger-add-delay-after-turning-on-D0-t.patch
0184-nope-fuck-the-last-few-binder-commits.patch
0183-staging-android-binder-fix-BC_FREE_BUFFER-ioctl-decl.patch
0182-android-binder-fix-BINDER_SET_MAX_THREADS-declaratio.patch
0181-staging-android-binder-replace-IOCTL-types-with-user.patch
0180-re-apply-epoll-fget_light-patches.patch
0179-cma-Remove-potential-deadlock-situation.patch
0178-Zram-Simplify-and-optimize-dev_to_zram-without-walki.patch
0177-zram-kill-unused-zram_get_num_devices-and-make-chang.patch
0176-zram-use-zram-lock-to-protect-zram_free_page-in-swap.patch
0175-Staging-Fixes-string-split-across-lines-in-zram.patch
0174-Revert-EPOLLWAKEUP-changes-to-fget-light-and-zsmallo.patch
0173-epoll-switch-simple-cases-of-fget_light-to-fdget.patch
0172-uio-convert-to-idr_alloc-and-Fix-UIO-device-registra.patch
0171-arch-arm-mach-msm-Changed-to-pull-up-the-ap2mdm_stat.patch
0170-arm-arch-mach-msm-Disable-the-mdm2ap_pbl_ready-pin-a.patch
0169-msm-msm_bus-Fix-the-type-error-causing-bandwidth-ove.patch
0168-sysctl-Dont-scan-for-the-leaks-on-headers-eliminate-.patch
0167-governor-cleanup-part-1.patch
0166-fixup-derpy-doubling-of-ktime-compare-again.patch
0165-restored-working-necessary-patches.patch
0164-reverted-to-MarkOne.patch
0163-im-gonna-rebase.patch
0162-fuck-it-reverted-kernel-locking-bullshit.patch
0161-msm-rpm-fix-memory-leak-and-locking-performance-issu.patch
0160-and-more-and-more-and-more.patch
0159-fixup-shmem-vmtruncate.patch
0158-fixup-mmap.patch
0157-nother-fix.patch
0156-yeesh.patch
0155-more-mass-fixing.patch
0154-there.patch
0153-this-is-lofty-i-better-revert-and-slow-down.patch
0152-more-overhauling.patch
0151-memcg-swap-mem_cgroup_move_swap_account-never-needs-.patch
0150-mm-memcg-move-reclaim_stat-into-lruvec.patch
0149-mm-fs-remove-truncate_range.patch
0148-finish-up-one-little-reverted-file.patch
0147-MASSIVE-slub-overhaul.patch
0146-make-get_unused_fd_flags-a-function.patch
0145-new-helper-iterate_fd.patch
0144-Replace-BUG_ON-with-WARN_ON-and-return-immediately-t.patch
0143-exec-reserve-full-virtual-stack-space-at-execve.patch
0142-keep-that-i-think-it-fixes-our-problemo.patch
0141-shit-revert-this.patch
0140-lglock-add-DEFINE_STATIC_LGLOCK.patch
0139-SQUASH-stop-using-delayed_work_pending-for-a-ton-of-.patch
0138-kprobes-fix-wait_for_kprobe_optimizer.patch
0137-chuckle.REVERT-futex-patch-AGAIN.-I-never-learn.patch
0136-fix-derpy-merge-line.patch
0135-im-not-sure-how-or-why-that-got-deleted.patch
0134-fixup-derpy-doubling-of-ktime-compare-and-updated-de.patch
0133-alucard-hotplug-keep-it-off-by-default-for-now.patch
0132-backport-some-rt-fixes.patch
0131-disabling-mc-scheduling-for-now-to-see-if-it-helps-o.patch
0130-fixed.patch
0129-fuck.patch
0128-fix-derp.patch
0127-derp.patch
0126-added-alucard-hotplug-for-the-added-benefit-of-extra.patch
0125-kernel-smp.c-on_each_cpu_cond-fix-warning-in-fallbac.patch
0124-futex-fix-kernel-doc-notation-and-spelling.patch
0123-vmlinux.lds.h-Allow-architectures-to-add-sections-to.patch
0122-ftrace-Sort-all-function-addresses-not-just-per-page.patch
0121-asm-generic-uaccess-Allow-arches-to-over-ride-__-get.patch
0120-asm-generic-headers-uaccess.h-to-conditionally-defin.patch
0119-asm-generic-dma-mapping-broken.h-Provide-dma_alloc_a.patch
0118-Bluetooth-Pick-the-RSS-value-from-advertising-event.patch
0117-Bluetooth-Avoid-re-authentication-for-secure-high-co.patch
0116-Bluetooth-handle-TX-power-level-read.patch
0115-Prop-CR-Bluetooth-Add-address-type-for-mgmt_ev_devic.patch
0114-Bluetooth-SNIFF-Avoid-sniff-while-SCO-to-address-IOT.patch
0113-posix-cpu-timers-dont-account-cpu-timer-after-stoppe.patch
0112-sched-fair-Let-minimally-loaded-cpu-balance-the-grou.patch
0111-squashed-tcp_fin-and-tcp-mem-updates-and-perf-Optimi.patch
0110-mm-thp-move-invariant-bug-check-out-of-loop.patch
0109-squashed-fixes-for-ringbuffer.patch
0108-seccomp-fix-memory-leak-on-filter-attach.patch
0107-spi_qsd-Add-Runtime-PM-support-to-debugfs.patch
0106-mm-filemap-mm-make-sendfile-2-killable.patch
0105-lib-lz4-Set-ARM_EFFICIENT_UNALIGNED_ACCESS.patch
0104-mutex-Add-a-delay-into-the-SPIN_ON_OWNER-wait-loop.patch
0103-cpuidle-Fix-nop-governor.patch
0102-cpuidle-Add-nop-idle-governor.patch
0101-ext4-rate-limit-printk-in-buffer_io_error.patch
0100-Remove-rest-of-exec-domains.patch
0099-arm-Remove-signal-translation-and-exec_domain.patch
0098-Remove-execution-domain-support.patch
0097-cpufreq-remove-the-sysfs-access-or-the-device-will-p.patch
0096-mm-zswap.c-change-params-from-hidden-to-ro-now-we-ca.patch
0095-zswap-use-LZ4-if-available.patch
0094-mm-use-managed_pages-to-calculate-default-zonelist-o.patch
0093-hrtimer-Prevent-stale-expiry-time-in-hrtimer_interru.patch
0092-s-push-sync_filesystem-down-to-every-filesystems-rem.patch
0091-arm-bpf_jit-remove-modules-dependence.patch
0090-net-netfilter-x_tables-reduce-logspam.patch
0089-net-add-sk_fullsock-helper.patch
0088-mm-vmscan-support-complete-shrinker-reclaim.patch
0087-PM-Documentation-Add-missing-freeze-state.patch
0086-PM-wakeup-Include-appropriate-header-file-in-kernel-.patch
0085-PM-sleep-Move-prototype-declaration-to-header-file.patch
0084-mm-use-totalram_pages-instead-of-num_physpages.patch
0083-PM-hibernate-memory-hotplug-Rework-mutual-exclusion.patch
0082-PM-hibernate-Create-memory-bitmaps-after-freezing-us.patch
0081-block_dev-implement-readpages-to-optimize-sequential.patch
0080-Squashed-hrtimer-optimization-commits.patch
0079-cpufreq-interactive-call-__cpufreq_driver_target-for.patch
0078-cpufreq-interactive-calculate-load-before-freq-chang.patch
0077-MASSIVE-locking-rwsem-percpu-rtmutex-squashed-update.patch
0076-percpu_rw_semaphore-New-percpu-lock-implementation.patch
0075-lglock-make-the-per_cpu-locks-static.patch
0074-lglock-remove-unused-DEFINE_LGLOCK_LOCKDEP.patch
0073-lockdep-fix-comment.patch
0072-lockdep-change-printk-to-pr_debug.patch
0071-Export-__lockdep_no_validate__.patch
0070-lockdep-Consolidate-bug-messages-into-a-single-print.patch
0069-lockdep-Print-out-additional-debugging-advice.patch
0068-lockdep-Remove-unnecessary-hlock_next-variable.patch
0067-lockdep-Print-more-info-when-MAX_LOCK_DEPTH-is-excee.patch
0066-lockdep-Rename-print_unlock_inbalance_bug-to-print.patch
0065-lockdep-Check-if-nested-lock-is-actually-held.patch
0064-kthread-fix-return-value-of-kthread_create-upon-SIGK.patch
0063-kthread-make-kthread_create-killable.patch
0062-EXPERIMENT-msm-acpuclock-krait-Init-to-max-speed-fas.patch
0061-block-Make-CFQ-default-to-IOPS-mode-on-SSDs.patch
0060-staging-android-Fixes-a-coding-style-issue-in-timed_.patch
0059-staging-android-Remove-whitespace-issue.patch
0058-msm-smd-add-smd_write_segment_avail-func.patch
0057-msm-smd-flush-pending-work-on-release.patch
0056-fs-get-rid-of-mnt_longterm.patch
0055-cgroup-cgroup_rm_files-was-calling-simple_unlink-wit.patch
0054-Revert-cgroup-superblock-cant-be-released-with-activ.patch
0053-cgroup-superblock-cant-be-released-with-active-dentr.patch
0052-mm-memcg-move-pc-lookup-point-to-commit_charge.patch
0051-memcg-fix-Bad-page-state-after-replace_page_cache.patch
0050-usb-ehci-msm-Fix-unclocked-access-on-system-resume.patch
0049-net-unix-sk_socket-fix-null-pointer-dereference.patch
0048-block-Drop-dead-function-blk_abort_queue.patch
0047-btrfs-Drop-unused-function-btrfs_abort_devices.patch
0046-PM-Enable-asynchronous-noirq-resume-threads.patch
0045-alarmtimer-fix-up-msecs-to-jiffies-code-in-wakeup.patch
0044-alarmtimer-change-wakeup-source-to-use-qtimer.patch
0043-clock-8960-crank-up-vcodec_clk-max-to-match-fmax.patch
0042-pstore-selinux-add-security-in-core-xattr-support-fo.patch
0041-revert-that.patch
0040-use-memzero-explicit-for-random.patch
0039-futex-Unlock-hb-lock-in-futex_wait_requeue_pi-error..patch
0038-ext4-dont-save-the-error-information-if-the-block-de.patch
0037-smd_pkt-Add-sanity-check-to-avoid-unregistering-the-.patch
0036-msm-smd_pkt-Remove-hexdump-of-userspace-read-write-b.patch
0035-of-move-of_get_cpu_node-implementation-to-DT-core.an.patch
0034-mdm-common-modem-increased-boot-timeout.patch
0033-sched-LOAD_FREQ-4-HZ-61-avoids-loadavg-Moire.closer-.patch
0032-a-knew-something-was-up-always-double-check-your-pat.patch
0031-freezer-Do-not-freeze-tasks-killed-by-OOM-killer.patch
0030-apq8064-add-generic-suspend-backoff-driver.patch
0029-reverted-it-all-except-brought-back-dynamic-standard.patch
0028-time-for-a-mass-reversion.patch
0027-oops-the-arguement-is-mode-not-the-enum-val.patch
0026-mdnie-hijack-modify-hijack-mDNIe_Set_Mode-function-w.patch
0025-update-mdnie-hijack-to-1.1-out-of-necessity.patch
0024-oops-part-two.patch
0023-oops.patch
0022-max-vals-not-ready-to-try-this-yet-from-a-safety-sta.patch
0021-attempt-at-adding-mdnie-hijack-1.0b-the-two-panels-a.patch
0020-jbd2-fix-assertion-failure-in-jbd2_journal_flush.patch
0019-otg-fixed-syntax.patch
0018-show-pvs-in-sysfs-thanks-Aaron.patch
0017-usb-otg-Check-ACA-before-handling-missed-id-interupt.patch
0016-updated-hellsactive-and-interactive-directly-from-he.patch
0015-REVERT-ext4-add-missing-save_error_info-to-ext4_erro.patch
0014-REVERT-fat-and-ext4-error-print-limit-reduction.patch
0013-cleanup.patch
0012-ext4-add-missing-save_error_info-to-ext4_error.patch
0011-fat-and-ext4-error-print-limit-reduction.patch
0010-fs-fuse-Add-replacment-for-CMA-pages-into-the-LRU-ca.patch
0009-rwsem-add-rwsem_is_contended.patch
0008-msm-sps-use-a-new-flag-for-disconnecting-pipe.patch
0007-scheduler-zen-fix-freeze-problem-on-init.patch
0006-sound-control-4.3-added-WORKING-bounds-check-thanks-.patch
0005-nevermind-that-breaks-it-set-it-with-an-init-script.patch
0004-sound-control-I-think-Ive-implemented-bounds-checkin.patch
0003-updated-kcal-driver-from-francos-changes-including-g.patch
0002-mdnie-made-sysfs-show-values-more-straightfoward-so-.patch
0001-leds-finally-getting-the-hang-of-this.patch
..
.
