#!/bin/bash
patch -p1 -R < "0129-mmc-core-Refactor-bus-speed-selection-code.patch"
patch -p1 -R < "0128-mmc-core-Enable-multiple-urgent-requests-notif.patch"
patch -p1 -R < "0127-mmc-msm_sdcc-fix-clock-gating-handling-using-pwrsave.patch"
patch -p1 -R < "0126-mmc-core-export-mmc_host_may_gate_card-function.patch"
patch -p1 -R < "0125-mmc-add-dynamic-trigger-for-packed-control.patch"
patch -p1 -R < "0124-mmc-core-Fix-updating-clock-scaling-statistics.patch"
patch -p1 -R < "0123-mmc-core-Fix-broken-clock-gating.patch"
patch -p1 -R < "0122-mmc-fix-wait-latency-of-urgent-request.patch"
patch -p1 -R < "0121-mmc-Add-support-to-handle-Urgent-data-transfer-reque.patch"
