#!/bin/bash

patch -p1 < "/root/machinex/patches/0153-fat-introduce-special-inode-for-managing-the-FSINFO.patch"
patch -p1 < "/root/machinex/patches/0154-fat-introduce-mark_fsinfo_dirty-helper.patch"
patch -p1 < "/root/machinex/patches/0155-fat-mark-superblock-as-dirty-less-often.patch"
patch -p1 < "/root/machinex/patches/0156-fat-switch-to-fsinfo_inode.patch"
patch -p1 < "/root/machinex/patches/0157-fat-add-fat_msg_ratelimit.patch"
patch -p1 < "/root/machinex/patches/0158-fat-use-fat_msg_ratelimit-in-fat__get_entry.patch"
patch -p1 < "/root/machinex/patches/0159-procfs-use-more-apprioriate-types-when-dumping.patch"
patch -p1 < "/root/machinex/patches/0160-proc-report-file-anon-bit-in-proc-pid-pagemap.patch"
patch -p1 < "/root/machinex/patches/0161-proc-smaps-carefully-handle-migration-entries.patch"
patch -p1 < "/root/machinex/patches/0162-proc-smaps-show-amount-of-nonlinear-ptes-in-vma.patch"
patch -p1 < "/root/machinex/patches/0163-fs-nls-add-Apple-NLS.patch"
patch -p1 < "/root/machinex/patches/0164-c-r-procfs-add-arg_start-end-env_start-end-and-exit_.patch"
patch -p1 < "/root/machinex/patches/0165-syscalls-x86-add-__NR_kcmp-syscall.patch"
patch -p1 < "/root/machinex/patches/0166-c-r-prctl-extend-PR_SET_MM-to-set-up-more-mm_structs.patch"
patch -p1 < "/root/machinex/patches/0167-c-r-prctl-add-ability-to-set-new-mm_struct-exe_file.patch"
patch -p1 < "/root/machinex/patches/0168-bs.patch"
patch -p1 < "/root/machinex/patches/0169-ext4-hole-punch-use-truncate_pagecache_range.patch"
patch -p1 < "/root/machinex/patches/0170-take-security_mmap_file-outside-of-mmap_sem.patch"
patch -p1 < "/root/machinex/patches/0171-move-security_mmap_addr-to-saner-place.patch"
patch -p1 < "/root/machinex/patches/0172-take-calculation-of-final-prot-in-security_mmap_file.patch"
patch -p1 < "/root/machinex/patches/0173-switch-aio-and-shm-to-do_mmap_pgoff-make-do_mmap-sta.patch"
patch -p1 < "/root/machinex/patches/0174-kill-do_mmap-completely.patch"
patch -p1 < "/root/machinex/patches/0175-unexport-do_munmap.patch"
patch -p1 < "/root/machinex/patches/0176-sch_atm.c-get-rid-of-poinless-extern.patch"
patch -p1 < "/root/machinex/patches/0177-fixed-where-i-done-fucked-up.patch"
patch -p1 < "/root/machinex/patches/0178-vfs-do_dentry_open-dont-put-filp.patch"
patch -p1 < "/root/machinex/patches/0187-i2c-Add-generic-I2C-multiplexer-using-pinctrl-API.patch"
patch -p1 < "/root/machinex/patches/0217-update-defconfig-with-apple-codepage-changes-again.patch"
patch -p1 < "/root/machinex/patches/0218-Bluetooth-Fix-coding-style-in-hci_sock.c.patch"
patch -p1 < "/root/machinex/patches/0219-more-bluetooth-codestyle.patch"
patch -p1 < "/root/machinex/patches/0220-Staging-android-alarm-Rename-pr_alarm-to-alarm_dbg.patch"

patch -p1 < "/root/machinex/patches/0254-shmem-replace_page-must-flush_dcache-and-others.patch"
patch -p1 < "/root/machinex/patches/0255-dox.patch"
patch -p1 < "/root/machinex/patches/0256-c-r-prctl-update-prctl_set_mm_exe_file-after-mm-num_.patch"
patch -p1 < "/root/machinex/patches/0257-c-r-prctl-add-minimal-address-test-to-PR_SET_MM.patch"
patch -p1 < "/root/machinex/patches/0258-c-r-prctl-add-ability-to-get-clear_tid_address.patch"
patch -p1 < "/root/machinex/patches/0259-c-r-prctl-drop-VMA-flags-test-on-PR_SET_MM_-stack.patch"
patch -p1 < "/root/machinex/patches/0260-ipc-shm-restore-MADV_REMOVE-functionality-on-shared-.patch"
patch -p1 < "/root/machinex/patches/0261-btree-catch-NULL-value-before-it-does-harm.patch"
patch -p1 < "/root/machinex/patches/0262-snmp-fix-OutOctets-counter-to-include-forwarded-data.patch"
patch -p1 < "/root/machinex/patches/0263-ext4-fix-the-free-blocks-calculation-for-ext3-file-s.patch"
patch -p1 < "/root/machinex/patches/0264-dma-dmaengine-add-slave-req-id-in-slave_config.patch"

patch -p1 < "/root/machinex/patches/0266-Revert-vfs-stop-d_splice_alias-creating-directory-al.patch"

patch -p1 < "/root/machinex/patches/0294-c-r-prctl-Move-PR_GET_TID_ADDRESS-to-a-proper-place.patch"
patch -p1 < "/root/machinex/patches/0295-mempool-add-gfp_mask-to-mempool_create_node.patch"
patch -p1 < "/root/machinex/patches/0296-block-drop-custom-queue-draining-used-by-scsi_transp.patch"
patch -p1 < "/root/machinex/patches/0297-block-refactor-get_request-_wait.patch"
patch -p1 < "/root/machinex/patches/0298-block-add-q-nr_rqs-and-move-q-rq.elvpriv-to-q-nr_rqs.patch"

