#!/bin/bash

patch -p1 -R < "/root/machinex/patches/0050-slimbus-add-ngd-to-config.patch"
patch -p1 -R < "/root/machinex/patches/0049-Slim_ngd-Modify-waiting-mechanism-in-kthread-and-Use.patch"
patch -p1 -R < "/root/machinex/patches/0048-slimbus-Enable-clients-to-send-user-messages-to-dev.patch"
patch -p1 -R < "/root/machinex/patches/0047-slim_ngd-Handle-error-flags-before-handling-SENT-fla.patch"
patch -p1 -R < "/root/machinex/patches/0046-slim_msm-Get-platform-specific-information-from-plat.patch"
patch -p1 -R < "/root/machinex/patches/0045-slim_msm-Signal-client-s-completion-per-transfer.patch"
patch -p1 -R < "/root/machinex/patches/0044-slim_msm-Report-flow-error-and-mask-apps-slimbus-por.patch"
patch -p1 -R < "/root/machinex/patches/0043-slim_ngd-Add-NULL-pointer-check-apart-from-error-che.patch"
patch -p1 -R < "/root/machinex/patches/0042-slim-ngd-NULL-pointer-check-for-client-buffer.patch"
patch -p1 -R < "/root/machinex/patches/0041-slim_ngd-Make-sure-transaction-is-not-dereferenced.patch"
patch -p1 -R < "/root/machinex/patches/0040-slim_ngd-Support-reserving-message-bandwidth.patch"
patch -p1 -R < "/root/machinex/patches/0039-slimbus-Handle-channel-control-correctly-if-controll.patch"
patch -p1 -R < "/root/machinex/patches/0038-slimbus-Refine-scope-of-controller-and-scheduler-mut.patch"
patch -p1 -R < "/root/machinex/patches/0037-slim_ngd-Rectify-define-removal-messages-per-protoco.patch"
patch -p1 -R < "/root/machinex/patches/0036-slimbus-ngd-remove-incompatible-feature.patch"
patch -p1 -R < "/root/machinex/patches/0035-slim_ngd-Slimbus-satellite-controller-driver.patch"
patch -p1 -R < "/root/machinex/patches/0034-slim_msm-Allow-remote-management-of-pipes-for-MSM.patch"
patch -p1 -R < "/root/machinex/patches/0033-slim_msm-Move-out-common-functionality-from-MSM.patch"
patch -p1 -R < "/root/machinex/patches/0032-slimbus-Add-slave-devices-to-controller-after-contro.patch"
patch -p1 -R < "/root/machinex/patches/0031-slimbus-add-local-header.patch"
