#!/bin/bash
/root/machinex/patches/0001-genirq-Fix-memory-leak-when-calling-irq_free_hwirqs.patch
/root/machinex/patches/0002-torture-Avoid-format-string-leak-to-thead-name.patch
/root/machinex/patches/0003-sched-numa-Stay-on-the-same-node-if-CLONE_VM.patch
/root/machinex/patches/0004-whitespace.patch
/root/machinex/patches/0005-fixup-sched_fork-type.patch
/root/machinex/patches/0006-sched-fair-implement-fast-idling-of-CPUs-when-the-sy.patch
/root/machinex/patches/0007-holy-shit-got-it.patch
/root/machinex/patches/0008-add-llist-for-each-entry-safe.patch
/root/machinex/patches/0009-REVERT-for-now-smp-add-new-wake_up_all_idle_cpus-fun.patch
/root/machinex/patches/0010-goddamn-have-to-update-gitignore.patch
/root/machinex/patches/0011-there-no-more-bc.patch
/root/machinex/patches/0012-updated-gitignore.patch
/root/machinex/patches/0013-Disable-ldo_retention.patch
/root/machinex/patches/0014-modules-use-raw_cpu_write-for-initialization-of-per-.patch
/root/machinex/patches/0015-rcu-Parallelize-and-economize-NOCB-kthread-wakeups.patch
/root/machinex/patches/0016-rcu-Don-t-offload-callbacks-unless-specifically-requ.patch
/root/machinex/patches/0017-dox.patch
/root/machinex/patches/0018-rcu-Make-rcu-node-arrays-static-const-char-const.patch
/root/machinex/patches/0019-rcu-Remove-redundant-ACCESS_ONCE-from-tick_do_timer.patch
/root/machinex/patches/0020-rcu-Eliminate-read-modify-write-ACCESS_ONCE-calls.patch
/root/machinex/patches/0021-rcu-Loosen-__call_rcu-s-rcu_head-alignment-constrain.patch
/root/machinex/patches/0022-rcu-Allow-post-unlock-reference-for-rt_mutex.patch
/root/machinex/patches/0023-rcu-Check-both-root-and-current-rcu_node.patch
/root/machinex/patches/0024-rcu-Simplify-priority-boosting.patch
/root/machinex/patches/0025-rcu-Bind-grace-period-kthreads-to-non-NO_HZ_FULL-CPU.patch
/root/machinex/patches/0026-rcu-Don-t-use-NMIs-to-dump-other-CPUs-stacks.patch
/root/machinex/patches/0027-rcu-Use-__this_cpu_read-instead-of-per_cpu_ptr.patch
/root/machinex/patches/0028-Remove-CONFIG_RCU_PROVE_DELAY.patch
/root/machinex/patches/0029-rcu-Fix-__rcu_reclaim-to-use-true-false-for-bool.patch
/root/machinex/patches/0030-rcu-Fix-a-sparse-warning-in-rcu_initiate_boost.patch
/root/machinex/patches/0031-rcu-Fix-a-sparse-warning-in-rcu_report_unblock_qs.patch
/root/machinex/patches/0032-cpuset-add-cs-effective_cpus-and-cs-effective_mems.patch
/root/machinex/patches/0033-cpuset-update-cpuset-effective_-cpus-mems-at-hotplug.patch
/root/machinex/patches/0034-revert-those.patch
/root/machinex/patches/0035-workqueue-reuse-the-already-calculated-pwq.patch
/root/machinex/patches/0036-locking-rwsem-Allow-conservative-optimistic-spinning.patch
/root/machinex/patches/0037-locking-spinlocks-mcs-Rename-optimistic_spin_queue-t.patch
/root/machinex/patches/0038-locking-spinlocks-mcs-Convert-osq-lock-to-atomic_t.patch
/root/machinex/patches/0039-locking-spinlocks-mcs-Introduce-and-use-init-macro.patch
/root/machinex/patches/0040-locking-spinlocks-mcs-Micro-optimize-osq_unlock.patch
/root/machinex/patches/0041-perf-Add-vm_ops-name-call-for-mmap-event-name-retrie.patch
/root/machinex/patches/0042-sched-Fix-possible-divide-by-zero-in-avg_atom-calc.patch
/root/machinex/patches/0043-sched-deadline-Kill-task_struct-pi_top_task.patch
/root/machinex/patches/0044-sched-Transform-resched_task-into-resched_curr.patch
/root/machinex/patches/0045-sched-rt-Fix-replenish_dl_entity-comments.patch
/root/machinex/patches/0046-sched-Remove-extra-static_key-function-indirection.patch
/root/machinex/patches/0047-sched-Fix-static_key-race-with-sched_feat.patch
/root/machinex/patches/0048-locking-rwsem-Rename-activity-to-count.patch
/root/machinex/patches/0049-locking-mutex-disable-optimiztic-spinning-on-some-ar.patch
/root/machinex/patches/0050-this-is-frustrating.patch
/root/machinex/patches/0051-reverted.patch
/root/machinex/patches/0052-locking-rwsem-Reduce-the-size-of-struct-rw_semaphore.patch
/root/machinex/patches/0053-locking-rwsem-Add-CONFIG_RWSEM_SPIN_ON_OWNER.patch
/root/machinex/patches/0054-rcu-Allow-for-NULL-tick_nohz_full_mask-when-nohz_ful.patch
/root/machinex/patches/0055-locking-lockdep-Only-ask-for-proc-lock_stat-output-w.patch
/root/machinex/patches/0056-hmm-maybe-not-yet.patch
/root/machinex/patches/0057-reverted.patch
/root/machinex/patches/0058-REVERT-perf-Add-vm_ops-name-call-for-mmap-event-name.patch
/root/machinex/patches/0059-smp-remove-cpuinitdata.patch
/root/machinex/patches/0060-genirq-generic-chip-Export-irq_map_generic_chip-func.patch
/root/machinex/patches/0061-the-fuck.patch
/root/machinex/patches/0062-reverted.patch
/root/machinex/patches/0063-sched-arch-Create-asm-preempt.h.patch
/root/machinex/patches/0064-just-fuckin-merging-all-the-preempt-shit.patch
/root/machinex/patches/0065-some-conversions.patch
/root/machinex/patches/0066-suck-it-this-may-not-work-but-regardless-i-am-callin.patch
/root/machinex/patches/0067-hardirq.patch
/root/machinex/patches/0068-core-preempt.patch
/root/machinex/patches/0069-No-NOKPROBE-yet.patch
/root/machinex/patches/0070-dont-need-should_resched-there-anymore.patch
/root/machinex/patches/0071-my-modules-still-need-access-to-preemption-calls.patch
/root/machinex/patches/0072-turning-off-pm-8x60-sync-timer-again.patch
/root/machinex/patches/0073-PM-sleep-Simplify-sleep-states-sysfs-interface-code.patch
/root/machinex/patches/0074-fuck-me.patch
/root/machinex/patches/0075-FUCK.patch
/root/machinex/patches/0076-reverted-AGAIN.patch
/root/machinex/patches/0077-i-swear-i-am-going-to-punch-a-hole-in-my-monitor.patch
/root/machinex/patches/0078-reverted-preempt-shit.patch
/root/machinex/patches/0079-think-i-might-have-finally-fucking-fixed-it.patch
/root/machinex/patches/0080-THERE-FUCK.patch
/root/machinex/patches/0081-HOW-ABOUT-NOW-FUCKER.patch
/root/machinex/patches/0082-i-am-getting-fucking-pissed-at-this-bullshit-preempt.patch
/root/machinex/patches/0083-possing.patch
/root/machinex/patches/0084-possed.patch
/root/machinex/patches/0085-disabled-sync_timer-again.patch
/root/machinex/patches/0086-sched-Fix-possible-divide-by-zero-in-avg_atom-calc.patch
/root/machinex/patches/0087-sched-deadline-Kill-task_struct-pi_top_task.patch
/root/machinex/patches/0088-conversion-to-resched_cur-WITHOUT-fucking-up-preempt.patch
/root/machinex/patches/0089-sched-Remove-extra-static_key-function-indirection.patch
/root/machinex/patches/0090-sched-Fix-static_key-race-with-sched_feat.patch
/root/machinex/patches/0091-Add-module-param-type-ullong-for-64-bit-vars.patch
/root/machinex/patches/0092-kernel-time-Add-udelay_test-module-to-validate.patch
/root/machinex/patches/0093-timekeeping-Simplify-arch_gettimeoffset.patch
/root/machinex/patches/0094-hrtimer-Cleanup-hrtimer-accessors-to-the-timekepeing.patch
/root/machinex/patches/0095-FUCK-THIS.patch
/root/machinex/patches/0096-REVERT-taht.patch
/root/machinex/patches/0097-oooh-i-like-this-WARN-when-shared-interrupts-do-not-.patch
/root/machinex/patches/0098-ARM-avoid-ARM-binutils-leaking-ELF-local-symbols.patch
/root/machinex/patches/0099-sched-numa-Use-select_idle_sibling.patch
/root/machinex/patches/0100-sched-Add-new-API-wake_up_if_idle-to-wake-up-the-idl.patch
/root/machinex/patches/0101-smp-Add-new-wake_up_all_idle_cpus-function.patch
/root/machinex/patches/0102-sched-rt-Remove-useless-if-from-cleanup-pick_next.patch
/root/machinex/patches/0103-sched-Fix-imbalance-flag-reset.patch
/root/machinex/patches/0104-sched-Remove-a-wake_affine-condition.patch
/root/machinex/patches/0105-REVERT-the-timer-commits.patch
/root/machinex/patches/0106-REVERT-the-majority-of-vfs-fs-commits-from-the-last-.patch
/root/machinex/patches/0107-REVERT-wake-up-if-idle-commits.patch
/root/machinex/patches/0108-smp-fix-call_function_single_async-locking.patch
/root/machinex/patches/0109-fix-error-case-in-handling-smp_call_function-Linus-s.patch
/root/machinex/patches/0110-bring-back-wake-up-if-idle-commits.patch
/root/machinex/patches/0111-from-Raphael-fix-barrier-on-context-switch.patch
/root/machinex/patches/0112-smpboot-Add-common-code-for-notification-from-dying-.patch
/root/machinex/patches/0113-smpboot-allow-excluding-cpus-from-the-smpboot-thread.patch
/root/machinex/patches/0114-smpboot-fix-memory-leak-on-error-handling.patch
/root/machinex/patches/0115-smpboot-make-cleanup-to-mirror-setup.patch
/root/machinex/patches/0116-nope.patch
/root/machinex/patches/0117-eyp.patch
/root/machinex/patches/0118-ARM-7872-1-Support-arch_irq_work_raise-via-self-IPIs.patch
/root/machinex/patches/0119-ARM-add-ipi-tracepoints.patch
/root/machinex/patches/0120-arm-tell-irq-work-about-self-ipi-support.patch
/root/machinex/patches/0121-ARM-collapse-arch_cpu_idle_dead-into-cpu_die.patch
/root/machinex/patches/0122-add-ipi-trace-header.patch
/root/machinex/patches/0123-do-not-trace-cpus-when-cpu-is-offline.patch
/root/machinex/patches/0124-add-some-cpu.h-backup.patch
/root/machinex/patches/0125-fix-hrtimer-hotplug-race.patch
/root/machinex/patches/0126-remove-traces-from-arm-smp.patch
/root/machinex/patches/0127-ARM-Remove-IPI_CALL_FUNC_SINGLE.patch
/root/machinex/patches/0128-minor-fix-ordering-of-arm-smp.patch
/root/machinex/patches/0129-TEST-acpuclock-I-am-disabling-the-spin-lock-held-for.patch
/root/machinex/patches/0130-perhaps-quickly-disabling-and-then-re-enabling-preem.patch
/root/machinex/patches/0131-this-probably-wont-work-but-I-have-attempted-convert.patch
/root/machinex/patches/0132-that-failed.patch
/root/machinex/patches/0133-gonna-try-save-restore-spins.patch
/root/machinex/patches/0134-oops-wrong-type.patch
/root/machinex/patches/0135-acpuclock-nope-that-has-to-be-a-spinlock-also-regula.patch
/root/machinex/patches/0136-acpuclock-krait-program-both-the-high-and-low-perfor.patch
/root/machinex/patches/0137-REVERT-msm-acpuclock-krait-Work-around-retention-cor.patch
/root/machinex/patches/0138-REVERT-high-and-low-performance-sources-to-test.patch
/root/machinex/patches/0139-oops-forgot-those-spinlocks.patch
/root/machinex/patches/0140-goddamn-slow-computer.patch
/root/machinex/patches/0141-correct-me-if-im-wrong-but-doesnt-it-make-sense-to-o.patch
/root/machinex/patches/0142-tracing-Replace-__get_cpu_var-uses-with-this_cpu_ptr.patch
/root/machinex/patches/0143-rcu-Parallelize-and-economize-NOCB-kthread-wakeups.patch
/root/machinex/patches/0144-rcu-Don-t-offload-callbacks-unless-specifically-req.patch
/root/machinex/patches/0145-rcu-Make-rcu-node-arrays-static-const-char-const.patch
/root/machinex/patches/0146-rcu-Remove-redundant-ACCESS_ONCE-from-tick_do_timer.patch
/root/machinex/patches/0147-msm-timer-restore-hz-usage.patch
/root/machinex/patches/0148-dox.patch
/root/machinex/patches/0149-workqueue-clear-POOL_DISASSOCIATED-in-rebind_workers.patch
/root/machinex/patches/0150-orkqueue-stronger-test-in-process_one_work.patch
/root/machinex/patches/0151-TEST-REVERT-msm-acpuclock-krait-Init-to-max-speed.patch
/root/machinex/patches/0152-rcu-Eliminate-read-modify-write-ACCESS_ONCE-calls.patch
/root/machinex/patches/0153-rcu-Loosen-__call_rcu-s-rcu_head-alignment-constrain.patch
/root/machinex/patches/0154-rcu-Allow-post-unlock-reference-for-rt_mutex.patch
/root/machinex/patches/0155-rcu-Check-both-root-and-current-rcu_node.patch
/root/machinex/patches/0156-rcu-Simplify-priority-boosting.patch
/root/machinex/patches/0157-rcu-Bind-grace-period-kthreads-to-non-NO_HZ_FULL-CPU.patch
/root/machinex/patches/0158-rcu-Don-t-use-NMIs-to-dump-other-CPUs-stacks.patch
/root/machinex/patches/0159-rcu-Use-__this_cpu_read-instead-of-per_cpu_ptr.patch
/root/machinex/patches/0160-Remove-CONFIG_PROVE_RCU_DELAY.patch
/root/machinex/patches/0161-PROVE_RCU_DELAY-removed-from-config.patch
/root/machinex/patches/0162-rcu-Fix-__rcu_reclaim-to-use-true-false-for-bool.patch
/root/machinex/patches/0163-rcu-Fix-a-sparse-warning-in-rcu_initiate_boost.patch
/root/machinex/patches/0164-rcu-Fix-a-sparse-warning-in-rcu_report_unblock_qs.patch
/root/machinex/patches/0165-Revert-irq-Warn-when-shared-interrupts-do-not-match-.patch
/root/machinex/patches/0166-genirq-Add-sanity-checks-for-PM-options-on-shared-in.patch
/root/machinex/patches/0167-genirq-Add-IRQ_SET_MASK_OK_DONE-to-support-stacked-i.patch
/root/machinex/patches/0168-locking-rwsem-Allow-conservative-optimistic-spinning.patch
/root/machinex/patches/0169-locking-spinlocks-mcs-Rename-optimistic_spin_queue-t.patch
/root/machinex/patches/0170-locking-spinlocks-mcs-Convert-osq-lock-to-atomic_t.patch
/root/machinex/patches/0171-locking-spinlocks-mcs-Introduce-and-use-init-macro.patch
/root/machinex/patches/0172-locking-spinlocks-mcs-Micro-optimize-osq_unlock.patch
/root/machinex/patches/0173-locking-rwsem-Rename-activity-to-count.patch
/root/machinex/patches/0174-rcu-Allow-for-NULL-tick_nohz_full_mask-when-nohz_ful.patch
/root/machinex/patches/0175-locking-lockdep-Only-ask-for-proc-lock_stat-output-w.patch
/root/machinex/patches/0176-arch-locking-rename-arch_mutex_cpu_relax-to-cpu_rela.patch
/root/machinex/patches/0177-genirq-generic-chip-Export-irq_map_generic_chip-func.patch
/root/machinex/patches/0178-PM-Sleep-Remove-ftrace_stop-start-from-suspend-and-h.patch
/root/machinex/patches/0179-ring-buffer-Always-run-per-cpu-ring-buffer-resize-wi.patch
/root/machinex/patches/0180-workqueue-wake-regular-worker-if-need_more_worker-wh.patch
/root/machinex/patches/0181-asmlinkage-Add-explicit-__visible-to-lots-of-stuff.patch
/root/machinex/patches/0182-timekeeping-Simplify-arch_gettimeoffset.patch
/root/machinex/patches/0183-hrtimer-Cleanup-hrtimer-accessors-to-timekeeping.patch
/root/machinex/patches/0184-ktime-kill-non-scalar-ktime_t.patch
/root/machinex/patches/0185-time64-Add-time64.h-header-and-define-struct-timespe.patch
/root/machinex/patches/0186-time-More-core-infrastructure-for-timespec64.patch
/root/machinex/patches/0187-timekeeping-Convert-timekeeping-core-to-use-timespec.patch
/root/machinex/patches/0188-time-Consolidate-the-time-accessor-prototypes.patch
/root/machinex/patches/0189-timekeeping-Provide-timespec64-based-interfaces.patch
/root/machinex/patches/0190-timekeeper-Move-tk_xtime-to-core-code.patch
/root/machinex/patches/0191-hold-up.patch
/root/machinex/patches/0192-ktime-Change-ktime_set-to-take-64bit-seconds-value.patch
/root/machinex/patches/0193-timekeeping-Cache-optimize-struct-timekeeper.patch
/root/machinex/patches/0194-timekeeping-Use-timekeeping_update-instead-of-memcpy.patch
/root/machinex/patches/0195-timekeeping-Provide-internal-ktime_t-based-data.patch
/root/machinex/patches/0196-timekeeping-Use-ktime_t-based-data-for-ktime_get.patch
/root/machinex/patches/0197-timekeeping-Provide-ktime_get_with_offset.patch
/root/machinex/patches/0198-timekeeping-Use-ktime_t-based-data-for-ktime_get_rea.patch
/root/machinex/patches/0199-timekeeping-Use-ktime_t-based-data-for-ktime_get_boo.patch
/root/machinex/patches/0200-timekeeping-Use-ktime_t-based-data-for-ktime_get_clo.patch
/root/machinex/patches/0201-timekeeping-Use-ktime-based-data-for-ktime_get_updat.patch
/root/machinex/patches/0202-timekeeping-Provide-ktime_mono_to_any.patch
/root/machinex/patches/0203-timekeeping-Remove-ktime_get_monotonic_offset.patch
/root/machinex/patches/0204-time-Export-nsecs_to_jiffies.patch
/root/machinex/patches/0205-sched-Make-task-real_start_time-nanoseconds-based.patch
/root/machinex/patches/0206-sched-Make-task-start_time-nanoseconds-based.patch
/root/machinex/patches/0207-delayacct-Make-accounting-nanosecond-based.patch
/root/machinex/patches/0208-delayacct-Remove-braindamaged-type-conversions.patch
/root/machinex/patches/0209-some-header-fixes.patch
/root/machinex/patches/0210-timekeeping-Remove-monotonic_to_bootbased.patch
/root/machinex/patches/0211-timekeeping-Use-ktime_get_boottime-for-get_monotonic.patch
/root/machinex/patches/0212-timekeeping-Simplify-getboottime.patch
/root/machinex/patches/0213-timekeeping-Remove-timekeeper.total_sleep_time.patch
/root/machinex/patches/0214-timekeeping-Simplify-timekeeping_clocktai.patch
/root/machinex/patches/0215-timekeeping-Provide-ktime_get_raw.patch
/root/machinex/patches/0216-clocksource-Make-delta-calculation-a-function.patch
/root/machinex/patches/0217-clocksource-Move-cycle_last-validation-to-core-code.patch
/root/machinex/patches/0218-clocksource-get-rid-of-cycle-last.patch
/root/machinex/patches/0219-timekeeping-Restructure-the-timekeeper-some-more.patch
/root/machinex/patches/0220-timekeeping-Create-struct-tk_read_base-and-use-it-in.patch
/root/machinex/patches/0221-timekeeping-Use-tk_read_base-as-argument-for-timekee.patch
/root/machinex/patches/0222-timekeeping-Provide-fast-and-NMI-safe-access.patch
/root/machinex/patches/0223-timekeeping-Minor-fixup-for-timespec64-timespec.patch
/root/machinex/patches/0224-timekeeping-Rework-frequency-adjustments.patch
/root/machinex/patches/0225-timekeeping-Use-cached-ntp_tick_length-when-accumula.patch
/root/machinex/patches/0226-ring-buffer-Use-rb_page_size-instead-of-open-coded.patch
/root/machinex/patches/0227-module-add-within_module-function.patch
/root/machinex/patches/0228-ktime-add-ms_to_ktime-and-ktime_add_ms-helpers.patch
/root/machinex/patches/0229-sched-Robustify-topology-setup.patch
/root/machinex/patches/0230-dox.patch
/root/machinex/patches/0231-PM-Hibernate-Create-a-Radix-Tree-to-store-memory-bit.patch
/root/machinex/patches/0232-PM-Hibernate-Add-memory_rtree_find_bit-function.patch
/root/machinex/patches/0233-PM-Hibernate-Implement-position-keeping-in-radix.patch
/root/machinex/patches/0234-namespaces-Use-task_lock-and-not-rcu-to-protect.patch
/root/machinex/patches/0235-fucking-broke-wakeup-reasons.patch
/root/machinex/patches/0236-fixed-wakeup-reasons.patch
/root/machinex/patches/0237-doubled.patch
/root/machinex/patches/0238-reverted.patch
/root/machinex/patches/0239-timekeeping-Provide-ktime_mono_to_any.patch
/root/machinex/patches/0240-input-evdev-Use-ktime_mono_to_real.patch
/root/machinex/patches/0241-misc-ioc4-Use-ktime_get_ns.patch
/root/machinex/patches/0242-fs-lockd-Use-ktime_get_ns.patch
/root/machinex/patches/0243-seqcount-Provide-raw_read_seqcount.patch
/root/machinex/patches/0244-seqcount-Add-raw_write_seqcount_latch.patch
/root/machinex/patches/0245-simple_xattr-permit-0-size-extended-attributes.patch
/root/machinex/patches/0246-timer-sysinfo-use-get_monotonic_boottime-instead-of-.patch
/root/machinex/patches/0247-fs-proc-uptime.c-uptime_proc_show-use-get_monotonic_.patch
/root/machinex/patches/0248-time-settimeofday-Validate-the-values-of-tv.patch
/root/machinex/patches/0249-this-will-probably-require-some-modification-else-wh.patch
/root/machinex/patches/0250-fuck-no-fs-update.patch
/root/machinex/patches/0251-msm-event-timer-pm-8x60-we-are-now-tracking-percpu.patch
/root/machinex/patches/0252-update-cycle_last-usage-in-arm_vsyscall-and-explicit.patch
/root/machinex/patches/0253-initializing-tkr-just-in-case.patch
/root/machinex/patches/0254-fixup-my-vsyscall-to-properly-call-the-read-clock-fu.patch
/root/machinex/patches/0255-cgroup-trivial-style-updates.patch
/root/machinex/patches/0256-cgroup-implement-cgroup_has_tasks.patch
/root/machinex/patches/0257-cgroup-reimplement-cgroup_transfer_tasks-without-usi.patch
/root/machinex/patches/0258-fuck-this-one.patch
/root/machinex/patches/0259-fucked.patch
/root/machinex/patches/0260-fuck-em-both-too.patch
/root/machinex/patches/0261-actually-keeping-those.patch
/root/machinex/patches/0262-actually-reverted-em-all.patch
/root/machinex/patches/0263-kernel-extable-fix-address-checks.patch
/root/machinex/patches/0264-cgroup-rename-cgroup_subsys_state-dput_work.patch
/root/machinex/patches/0265-nope.patch
/root/machinex/patches/0266-nope-gonna-do-some-work-here.patch
/root/machinex/patches/0267-reverted-all-the-cgroupy-shit.patch
/root/machinex/patches/0268-REVERT-sched-task-start_time-and-task-real_start_tim.patch
/root/machinex/patches/0269-cheat-and-use-get_monotonic_boottime-with-kernel-for.patch
/root/machinex/patches/0270-oops-fixup-cgroup-timespec_compare.patch
/root/machinex/patches/0271-mdp.c-fix-call-to-event_timer.patch
/root/machinex/patches/0272-possing.patch
/root/machinex/patches/0273-possed.patch
/root/machinex/patches/0274-acct-encode_comp_t-0-is0.patch
/root/machinex/patches/0275-kernel-kallsyms.c-fix-pB-when-there-s-no-symbol.patch
/root/machinex/patches/0276-kernel-exit.c-fix-coding-style.patch
/root/machinex/patches/0277-sched-fair-Make-calculate_imbalance-independent.patch
/root/machinex/patches/0278-sched-fair-Make-update_sd_pick_busiest-return-true.patch
/root/machinex/patches/0279-sched-fair-Allow-calculate_imbalance-to-move-idle-cp.patch
/root/machinex/patches/0280-sched-Rename-a-misleading-variable-in-build_overlap.patch
/root/machinex/patches/0281-locking-Remove-deprecated-smp_mb__-barriers.patch
/root/machinex/patches/0282-locking-mutexes-Standardize-arguments-in-lock-unlock.patch
/root/machinex/patches/0283-locking-mutexes-Document-quick-lock-release.patch
/root/machinex/patches/0284-locking-mcs-Remove-obsolete-comment.patch
/root/machinex/patches/0285-locking-mutexes-Refactor-optimistic-spinning-code.patch
/root/machinex/patches/0286-locking-mutexes-Use-MUTEX_SPIN_ON_OWNER-when-appr.patch
/root/machinex/patches/0287-dox.patch
/root/machinex/patches/0288-locking-lockdep-Restrict-the-use-of-recursive-read.patch
/root/machinex/patches/0289-sched-Match-declaration-with-definition.patch
/root/machinex/patches/0290-sched-fair-Fix-reschedule-which-is-generated-on-thro.patch
/root/machinex/patches/0291-hold-up.patch
/root/machinex/patches/0292-sched-fair-fix-doubled-function-in-task_numa_compare.patch
/root/machinex/patches/0293-move-group-type-enum.patch
/root/machinex/patches/0294-not-yet.patch
/root/machinex/patches/0295-reverted.patch
/root/machinex/patches/0296-ref.patch
/root/machinex/patches/0297-sched-numa-Introduce-migrate_swap.patch
/root/machinex/patches/0298-sched-add-wrapper-for-cehcking-task-struct-on-rq.patch
/root/machinex/patches/0299-fixup.patch
/root/machinex/patches/0300-fixup-my-deadline-select_task_rq-with-cpu-included-i.patch
/root/machinex/patches/0301-teach-scheduler-to-understand-task-on-rq-migrating.patch
/root/machinex/patches/0302-sched-Add-function-single_task_running-to-let-a-task.patch
/root/machinex/patches/0303-scheduler-a-bunch-of-replacements-of-get-cpu-var-wit.patch
/root/machinex/patches/0304-already-had-task-on-rq-migrating.patch
/root/machinex/patches/0305-revert-the-get-cpu-var-replacements-for-a-moment-whi.patch
/root/machinex/patches/0306-brought-back-my-time-changes-from-yesterday-gonna-le.patch
/root/machinex/patches/0307-part-2.patch
/root/machinex/patches/0308-ktime-add-ms_to_ktime-and-ktime_add_ms-helpers.patch
/root/machinex/patches/0309-the-other-time-related-necessities.patch
/root/machinex/patches/0310-brought-back-this_cpu_ptr.patch
/root/machinex/patches/0311-header-fixes.patch
/root/machinex/patches/0312-fix-doubled.patch
/root/machinex/patches/0313-ohhh-right-that-was-thrown-in-the-mix.patch
/root/machinex/patches/0314-nope-time-is-a-dud.patch
/root/machinex/patches/0315-rcu-Make-nocb-leader-kthreads-process-pending-cbs.patch
/root/machinex/patches/0316-dox.patch
/root/machinex/patches/0317-genirq-Distangle-edge-handler-entry-.If-the-interrup.patch
/root/machinex/patches/0318-genirq-Create-helper-for-flow-handler-entry-check.patch
/root/machinex/patches/0319-genirq-Mark-wakeup-sources-as-armed-on-suspend.patch
/root/machinex/patches/0320-hold-up-again.patch
/root/machinex/patches/0321-revert-that.patch
/root/machinex/patches/0322-hmmm.patch
/root/machinex/patches/0323-reverted.patch
/root/machinex/patches/0324-alright-changed-irq-pm.patch
/root/machinex/patches/0325-k-there-fixed-the-header-too.patch
/root/machinex/patches/0326-genirq-Add-irq_domain-aware-core-IRQ-handler.patch
/root/machinex/patches/0327-locking-semaphore-Resolve-some-shadow-warnings.patch
/root/machinex/patches/0328-nohz-Restore-NMI-safe-local-irq-work-for-local-nohz.patch
/root/machinex/patches/0329-resources-Add-device-managed-request-release_res.patch
/root/machinex/patches/0330-rcu-Remove-remaining-read-modify-write-ACCESS_ONCE.patch
/root/machinex/patches/0331-rcu-Fix-sparse-warning-about-rcu_batches_completed.patch
/root/machinex/patches/0332-rcu-Use-bool-type-for-return-value-in-rcu_is_watchin.patch
/root/machinex/patches/0333-rcu-Return-bool-type-for-rcu_try_advance_all_cbs.patch
/root/machinex/patches/0334-rcu-Use-true-false-instead-of-1-0-for-a-bool-type.patch
/root/machinex/patches/0335-rcu-Uninline-rcu_read_lock_held.patch
/root/machinex/patches/0336-rcu-Update-tiny.c-references-to-tree.c.patch
/root/machinex/patches/0337-dox.patch
/root/machinex/patches/0338-rcu-Break-more-call_rcu-deadlock-involving-scheduler.patch
/root/machinex/patches/0339-rcu-Use-rcu_gp_kthread_wake-to-wake-up-grace-period.patch
/root/machinex/patches/0340-rcu-Replace-flush_signals-with-WARN_ON-signal_pendin.patch
/root/machinex/patches/0341-rcutorture-Fix-a-sparse-warning.patch
/root/machinex/patches/0342-pr_foo-converts.patch
/root/machinex/patches/0343-rcu-Add-call_rcu_tasks.patch
/root/machinex/patches/0344-rcu-Provide-cond_resched_rcu_qs-to-force-quiescent-s.patch
/root/machinex/patches/0345-rcu-Add-synchronous-grace-period-waiting-for-RCU.patch
/root/machinex/patches/0346-rcu-Make-TASKS_RCU-handle-tasks-that-are-almost-done.patch
/root/machinex/patches/0347-rcu-Export-RCU-tasks-APIs-to-GPL-modules.patch
/root/machinex/patches/0348-rcutorture-Add-torture-tests-for-RCU-tasks.patch
/root/machinex/patches/0349-rcu-Add-stall-warning-checks-for-RCU-tasks.patch
/root/machinex/patches/0350-rcu-Improve-RCU-tasks-energy-efficiency.patch
/root/machinex/patches/0351-rcu-Defer-rcu_tasks_kthread-creation-till-first-call.patch
/root/machinex/patches/0352-rcu-Make-TASKS_RCU-handle-nohz_full-CPUs.patch
/root/machinex/patches/0353-rcu-Make-rcu_tasks_kthread-s-GP-wait-loop-allow-pree.patch
/root/machinex/patches/0354-dox.patch
/root/machinex/patches/0355-rcu-Remove-local_irq_disable-in-rcu_preempt_note_con.patch
/root/machinex/patches/0356-rcu-Per-CPU-operation-cleanups-to-rcu_-_qs-functions.patch
/root/machinex/patches/0357-exit-Always-reap-resource-stats-in-__exit_signal.patch
/root/machinex/patches/0358-time-signal-Protect-resource-use-statistics-with-seq.patch
/root/machinex/patches/0359-sched-time-Atomically-increment-stime-utime.patch
/root/machinex/patches/0360-PM-sleep-Support-freeze-as-test_suspend-option.patch
/root/machinex/patches/0361-sched-Migrate-waking-tasks.patch
/root/machinex/patches/0362-nohz-Move-nohz-full-init-call-to-tick-init.patch
/root/machinex/patches/0363-irq_work-Force-raised-irq-work-to-run-on-irq-work-in.patch
/root/machinex/patches/0364-nohz-Consolidate-nohz-full-init-code.patch
/root/machinex/patches/0365-nohz-nohz-full-depends-on-irq-work-self-IPI-support.patch
/root/machinex/patches/0366-locking-rwsem-Move-EXPORT_SYMBOL-lines-to-follow-fun.patch
/root/machinex/patches/0367-rcu-Fix-attempt-to-avoid-unsolicited-offloading-of-c.patch
/root/machinex/patches/0368-use-true-and-false-for-bools.patch
/root/machinex/patches/0369-rcu-Use-false-for-return-in-__call_rcu_nocb.patch
/root/machinex/patches/0370-more.patch
/root/machinex/patches/0371-rcu-Rationalize-kthread-spawning.patch
/root/machinex/patches/0372-rcu-Create-rcuo-kthreads-only-for-onlined-CPUs.patch
/root/machinex/patches/0373-rcu-Check-for-have_rcu_nocb_mask-instead-of-rcu_nocb.patch
/root/machinex/patches/0374-replace-sysidle_state-with-our-new-one.patch
/root/machinex/patches/0375-rcu-Don-t-track-sysidle-state-if-no-nohz_full-CPUs.patch
/root/machinex/patches/0376-locktorture-Rename-locktorture_runnable-parameter.patch
/root/machinex/patches/0377-torture-squash.patch
/root/machinex/patches/0378-rcu-Eliminate-deadlock-between-CPU-hotplug-and-expid.patch
/root/machinex/patches/0379-sched-fair-cleanup-Remove-useless-assignment.patch
/root/machinex/patches/0380-sched-core-Use-put_prev_task-accessor-where-possible.patch
/root/machinex/patches/0381-sched-Do-not-stop-cpu-in-set_cpus_allowed_ptr.patch
/root/machinex/patches/0382-init-main.c-Give-init_task-a-canary.patch
/root/machinex/patches/0383-sched-Add-helper-for-task-stack-page-overrun-check.patch
/root/machinex/patches/0384-sched-Add-default-disabled-option-to-BUG-when-stack-.patch
/root/machinex/patches/0385-sched-Test-the-CPU-s-capacity-in-wake_affine.patch
/root/machinex/patches/0386-fix-some-typos-grammer.patch
/root/machinex/patches/0387-did-i-have-this-sched-Let-the-scheduler-see-CPU-idle.patch
/root/machinex/patches/0388-i-think-so.patch
/root/machinex/patches/0389-some-sched-tinkering.patch
/root/machinex/patches/0390-sched-Fix-a-race-between-__kthread_bind-and-sched-in.patch
/root/machinex/patches/0391-updated-config.patch
/root/machinex/patches/0392-fixup-my-__migrate_tasks.patch
/root/machinex/patches/0393-seqlock-Add-irqsave-variant-of-read_seqbegin_or_lock.patch
/root/machinex/patches/0394-irq_work-Introduce-arch_irq_work_has_interrupt.patch
/root/machinex/patches/0395-there-we-go-i-was-looking-in-the-wrong-place-for-thr.patch
/root/machinex/patches/0396-guess-we-dont-have-this.patch
/root/machinex/patches/0397-demand-govs-set_cpus_allowed-was-only-a-call-to-set_.patch
/root/machinex/patches/0398-right-now-that-we-are-using-the-pointer-directly-we-.patch
/root/machinex/patches/0399-small-possing.patch
/root/machinex/patches/0400-possed.patch
/root/machinex/patches/0401-bring-back-arch_irq_work_ahs_interrupt.patch
/root/machinex/patches/0402-bigger-pos.patch
/root/machinex/patches/0403-bigger-pos-for-real.patch
/root/machinex/patches/0404-there-possed.patch
/root/machinex/patches/0405-Revert-the-revert-of-get-cpu-var-replacements.patch
/root/machinex/patches/0406-rcu-Make-nocb-leader-kthreads-process-pending-cbs.patch
/root/machinex/patches/0407-dox.patch
/root/machinex/patches/0408-genirq-Distangle-edge-handler-entry.patch
/root/machinex/patches/0409-genirq-Create-helper-for-flow-handler-entry-check.patch
/root/machinex/patches/0410-locking-semaphore-Resolve-some-shadow-warnings.patch
/root/machinex/patches/0411-reverted-genirq-stuff-i-am-happy-with-my-irqs-on-sus.patch
/root/machinex/patches/0412-nohz-Restore-NMI-safe-local-irq-work-for-local-nohz.patch
/root/machinex/patches/0413-resources-Add-device-managed-request-release_res.patch
/root/machinex/patches/0414-rcu-Remove-remaining-read-modify-write-ACCESS_ONCE.patch
/root/machinex/patches/0415-rcu-Fix-sparse-warning-about-rcu_batches_completed.patch
/root/machinex/patches/0416-rcu-Use-bool-type-for-return-value-in-rcu_is_watchin.patch
/root/machinex/patches/0417-rcu-squash-up-to-pr_foo-converts.patch
/root/machinex/patches/0418-timekeeping-Simplify-arch_gettimeoffset.patch
/root/machinex/patches/0419-cpus_active-makes-more-sense-from-the-scheduling-cod.patch
/root/machinex/patches/0420-I-think-it-may-be-a-good-idea-to-remove-get-put-onli.patch
/root/machinex/patches/0421-hrtimer-Cleanup-hrtimer-accessors-to-timekeeping.patch
/root/machinex/patches/0422-wakeup-reason-fixed-time-logging-properly-and-remove.patch
/root/machinex/patches/0423-rcu-Add-call_rcu_tasks.patch
/root/machinex/patches/0424-rcu-Provide-cond_resched_rcu_qs-to-force-quiescent-s.patch
/root/machinex/patches/0425-rcu-Add-synchronous-grace-period-waiting-for-RCU.patch
/root/machinex/patches/0426-rcu-Make-TASKS_RCU-handle-tasks-that-are-almost-done.patch
/root/machinex/patches/0427-rcu-Export-RCU-tasks-APIs-to-GPL-modules.patch
/root/machinex/patches/0428-rcu-squash-up-to-rcu-Per-CPU-operation-cleanups-to-r.patch
/root/machinex/patches/0429-turn-OFF-tasks-rcu-this-round.patch
/root/machinex/patches/0430-more-suspend-time-fixin.patch
/root/machinex/patches/0431-ktime-kill-non-scalar-ktime_t.patch
/root/machinex/patches/0432-did-some-cleaning.patch
/root/machinex/patches/0433-time64-Add-time64.h-header-and-define-struct-timespe.patch
/root/machinex/patches/0434-time-More-core-infrastructure-for-timespec64.patch
/root/machinex/patches/0435-timekeeping-Convert-timekeeping-core-to-use-timespec.patch
/root/machinex/patches/0436-time-Consolidate-the-time-accessor-prototypes.patch
/root/machinex/patches/0437-timekeeping-Provide-timespec64-based-interfaces.patch
/root/machinex/patches/0438-timekeeper-Move-tk_xtime-to-core-code.patch
/root/machinex/patches/0439-seqcount-changes-for-timekeeper.patch
/root/machinex/patches/0440-ktime-Change-ktime_set-to-take-64bit-seconds-value.patch
/root/machinex/patches/0441-timekeeping-Cache-optimize-struct-timekeeper.patch
/root/machinex/patches/0442-ktime-add-ms_to_ktime-and-ktime_add_ms-helpers.patch
/root/machinex/patches/0443-timekeeping-Use-timekeeping_update-instead-of-memcpy.patch
/root/machinex/patches/0444-timekeeping-Provide-internal-ktime_t-based-data.patch
/root/machinex/patches/0445-timekeeping-Use-ktime_t-based-data-for-ktime_get.patch
/root/machinex/patches/0446-timekeeping-Provide-ktime_get_with_offset.patch
/root/machinex/patches/0447-ktime-t-shit.patch
/root/machinex/patches/0448-time-Export-nsecs_to_jiffies.patch
/root/machinex/patches/0449-move-around-adj_timex.patch
/root/machinex/patches/0450-nope-reverted-timer-shit-again.patch
