#!/bin/bash
patch -p1 < "/root/machinex/patches/0001-fucking-meld.patch"
patch -p1 < "/root/machinex/patches/0002-reverted.patch"
patch -p1 < "/root/machinex/patches/0003-as-it-would-turn-out-thermal_limit_high-is-just-the-.patch"
patch -p1 < "/root/machinex/patches/0004-now-that-the-cpufreq-api-probably-isnt-going-to-go-t.patch"
patch -p1 < "/root/machinex/patches/0005-same-with-governors.patch"
patch -p1 < "/root/machinex/patches/0006-for-starters-remove-disabled-checks-because-we-are-n.patch"
patch -p1 < "/root/machinex/patches/0007-remove-have-governor-per-policy-because-we-always-wi.patch"
patch -p1 < "/root/machinex/patches/0008-a-little-bit-of-interactive-tweaking-but-this-driver.patch"
patch -p1 < "/root/machinex/patches/0009-oops-added-cpufreq_suspended-to-cpufreq.h-while-thin.patch"
patch -p1 < "/root/machinex/patches/0010-what-better-a-place-to-call-suspend-and-resume-for-h.patch"
patch -p1 < "/root/machinex/patches/0011-fix-a-missing-include-for-hp.patch"
patch -p1 < "/root/machinex/patches/0012-need-to-do-some-debugging.patch"
patch -p1 < "/root/machinex/patches/0013-I-think-NR_CPUS-is-right.patch"

