--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -482,3 +482,4 @@ obj-$(CONFIG_BT_BCM4335) += board-bluetooth-bcm4335.o
 obj-$(CONFIG_BT_BCM4334) += board-bluetooth-bcm4334.o
 
 obj-$(CONFIG_FORCE_FAST_CHARGE) += fastchg.o
+obj-$(CONFIG_HAS_MACH_MEMUTILS) += memutils/
