#
# Makefile for kernel slimbus framework.
#
obj-$(CONFIG_SLIMBUS)			+= slimbus.o
obj-$(CONFIG_SLIMBUS2)			+= slimbus2.o
obj-$(CONFIG_SLIMBUS_MSM_CTRL)		+= slim-msm-ctrl.o
obj-$(CONFIG_SLIMBUS_MSM_CTRL2)		+= slim-msm.o slim-msm-ctrl.o slim-msm-ngd.o
