/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

/* Precomputed fixed inverse multiplies for multiplication by y^n */
static const u32 runnable_avg_yN_inv[] = {
	0xffff, 0xf524, 0xeabf, 0xe0cb, 0xd744, 0xce23, 0xc566, 0xbd07,
	0xb504, 0xad57, 0xa5fe, 0x9ef4, 0x9837, 0x91c3, 0x8b95, 0x85aa,
};

#define LOAD_AVG_PERIOD 16
#define LOAD_AVG_MAX 24117 /* maximum possible load avg */
#define LOAD_AVG_MAX_N 172 /* number of full periods to produce LOAD_AVG_MAX */
